### PR TITLE
Fix CI by removing an invalid test case

### PR DESCRIPTION
**Pull request by mazen160**

### CODE REVIEW

**Comment by mazen160** [comment]
I removed an invalid test case where I beautified a JSON test file (trufflehog output is nd-json). It should be ready to go.

**Comment by mazen160** [comment]
cc @arkadiyt @alexbod

**Comment by arkadiyt** [comment]
@mazen160 please don't merge PRs without at least 1 approval

**Comment by mazen160** [comment]
@arkadiyt I agree, just thought it's too simple to request code review

**Pull request merged**
